# Generated by Django 5.0.4 on 2024-04-28 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('slug', models.SlugField(unique=True, verbose_name='слаг')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(unique=True, verbose_name='слаг')),
                ('description', models.TextField(verbose_name='описание товара')),
                ('created', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='категория')),
            ],
        ),
    ]
