# Generated by Django 5.0.4 on 2024-04-29 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_image_mainimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.TextField(choices=[('Да', 'Опубликовано'), ('Нет', 'Черновик')], default='Да', max_length=3, verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='catalog.product', verbose_name='товар'),
        ),
    ]
